#!/usr/bin/env node
// Polyrule — write your AI coding rules once, compile them for every assistant.
// Zero dependencies. Requires Node 18+.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const RULES_DIR = path.join(ROOT, "rules");
const TARGETS = readJson(path.join(ROOT, "config", "targets.json"));
const PRESETS = readJson(path.join(ROOT, "config", "presets.json"));

function readJson(p) {
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

// ---------- CLI ----------

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith("--")) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (next === undefined || next.startsWith("--")) {
        args[key] = true;
      } else {
        args[key] = next;
        i++;
      }
    } else {
      args._.push(a);
    }
  }
  return args;
}

function list(val) {
  if (!val || val === true) return [];
  return String(val)
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

// ---------- Frontmatter parser (minimal, no deps) ----------

function parseRuleFile(filePath) {
  const raw = fs.readFileSync(filePath, "utf8");
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(raw);
  if (!match) {
    return { meta: {}, body: raw.trim() };
  }
  const meta = parseFrontmatter(match[1]);
  const body = match[2].trim();
  return { meta, body };
}

function parseFrontmatter(block) {
  const meta = {};
  for (const line of block.split(/\r?\n/)) {
    const m = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line);
    if (!m) continue;
    const key = m[1];
    let value = m[2].trim();
    if (value.startsWith("[") && value.endsWith("]")) {
      meta[key] = value
        .slice(1, -1)
        .split(",")
        .map((s) => unquote(s.trim()))
        .filter(Boolean);
    } else {
      meta[key] = unquote(value);
    }
  }
  return meta;
}

function unquote(s) {
  if (
    (s.startsWith('"') && s.endsWith('"')) ||
    (s.startsWith("'") && s.endsWith("'"))
  ) {
    return s.slice(1, -1);
  }
  return s;
}

// ---------- Rule resolution ----------

function resolvePreset(name, seen = new Set()) {
  const preset = PRESETS[name];
  if (!preset) {
    throw new Error(`Unknown preset: "${name}". Run --list to see options.`);
  }
  if (seen.has(name)) {
    throw new Error(`Circular preset extension detected at "${name}".`);
  }
  seen.add(name);
  let rules = [];
  if (preset.extends) {
    rules = rules.concat(resolvePreset(preset.extends, seen));
  }
  rules = rules.concat(preset.rules || []);
  return rules;
}

function dedupe(items) {
  const seen = new Set();
  const out = [];
  for (const item of items) {
    if (!seen.has(item)) {
      seen.add(item);
      out.push(item);
    }
  }
  return out;
}

function loadRules(ruleIds) {
  return ruleIds.map((id) => {
    const filePath = path.join(RULES_DIR, `${id}.md`);
    if (!fs.existsSync(filePath)) {
      throw new Error(`Rule not found: "${id}" (looked in ${filePath})`);
    }
    const parsed = parseRuleFile(filePath);
    return { id, ...parsed };
  });
}

// ---------- Formatters ----------

const HEADER =
  "<!-- Generated by Polyrule. Edit modules in /rules and recompile; do not edit this file by hand. -->";

function formatMarkdown(rules) {
  const sections = rules.map((r) => {
    const title = r.meta.title || r.id;
    return `## ${title}\n\n${r.body}`;
  });
  return `${HEADER}\n\n# Project Rules\n\n${sections.join("\n\n")}\n`;
}

function formatMdc(rules) {
  const globs = dedupe(rules.flatMap((r) => r.meta.globs || []));
  const body = rules
    .map((r) => `## ${r.meta.title || r.id}\n\n${r.body}`)
    .join("\n\n");
  const fm = [
    "---",
    "description: Project rules compiled by Polyrule",
    `globs: ${globs.join(", ")}`,
    "alwaysApply: true",
    "---",
  ].join("\n");
  return `${fm}\n\n${body}\n`;
}

function render(format, rules) {
  switch (format) {
    case "mdc":
      return formatMdc(rules);
    case "markdown":
    default:
      return formatMarkdown(rules);
  }
}

// ---------- Commands ----------

function printList() {
  console.log("\nPresets:");
  for (const [name, p] of Object.entries(PRESETS)) {
    console.log(`  ${name.padEnd(18)} ${p.description || ""}`);
  }
  console.log("\nTargets:");
  for (const [name, t] of Object.entries(TARGETS)) {
    console.log(`  ${name.padEnd(18)} ${t.name} -> ${t.output}`);
  }
  console.log("\nRule modules:");
  for (const id of allRuleIds()) {
    console.log(`  ${id}`);
  }
  console.log("");
}

function allRuleIds() {
  const ids = [];
  const walk = (dir, prefix) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        walk(path.join(dir, entry.name), `${prefix}${entry.name}/`);
      } else if (entry.name.endsWith(".md")) {
        ids.push(`${prefix}${entry.name.replace(/\.md$/, "")}`);
      }
    }
  };
  walk(RULES_DIR, "");
  return ids.sort();
}

// Validate the whole catalog: rule frontmatter, presets, and targets.
// Returns the number of problems found (0 = healthy).
function runCheck() {
  const problems = [];
  const ruleIds = allRuleIds();

  // Rules: required frontmatter + parseable body.
  for (const id of ruleIds) {
    const { meta, body } = parseRuleFile(path.join(RULES_DIR, `${id}.md`));
    if (!meta.id) problems.push(`rule "${id}": missing frontmatter "id"`);
    if (meta.id && meta.id !== path.basename(id))
      problems.push(`rule "${id}": frontmatter id "${meta.id}" does not match filename`);
    if (!meta.title) problems.push(`rule "${id}": missing frontmatter "title"`);
    if (!body.trim()) problems.push(`rule "${id}": empty body`);
  }

  // Presets: resolve (catches bad extends/cycles) and confirm every rule exists.
  const known = new Set(ruleIds);
  for (const name of Object.keys(PRESETS)) {
    try {
      for (const rid of resolvePreset(name)) {
        if (!known.has(rid))
          problems.push(`preset "${name}": references unknown rule "${rid}"`);
      }
    } catch (err) {
      problems.push(`preset "${name}": ${err.message}`);
    }
  }

  // Targets: required fields + known format.
  const formats = new Set(["markdown", "mdc"]);
  for (const [name, t] of Object.entries(TARGETS)) {
    if (!t.name) problems.push(`target "${name}": missing "name"`);
    if (!t.output) problems.push(`target "${name}": missing "output"`);
    if (!formats.has(t.format))
      problems.push(`target "${name}": unknown format "${t.format}"`);
  }

  if (problems.length) {
    console.error(`Polyrule check: ${problems.length} problem(s) found\n`);
    for (const p of problems) console.error(`  - ${p}`);
    return problems.length;
  }
  console.log(
    `Polyrule check: OK (${ruleIds.length} rules, ${Object.keys(PRESETS).length} presets, ${Object.keys(TARGETS).length} targets)`
  );
  return 0;
}

const HELP = `
Polyrule — write your AI coding rules once, compile them for every assistant.

Usage:
  node compile.mjs [options]

Options:
  --preset <name>      Use a named preset (see --list).
  --rules <a,b,c>      Comma-separated rule modules (e.g. core/security-baseline,languages/python).
  --target <t,t|all>   One or more targets, or "all". Default: all.
  --out <dir>          Output directory. Default: current directory.
  --config <file>      Read options from a JSON config. Default: polyrule.config.json (if present).
  --dry-run            Print what would be written without touching the filesystem.
  --check              Validate all rules, presets, and targets (exits non-zero on problems).
  --list               List presets, targets, and rule modules.
  --help               Show this help.

Examples:
  node compile.mjs --preset nextjs-fullstack --target cursor,claude
  node compile.mjs --rules core/security-baseline,languages/go --target all
  node compile.mjs                # uses ./polyrule.config.json
`;

function resolveConfig(args) {
  // Precedence: explicit CLI rules/preset > config file.
  let ruleIds = [];
  let targets = list(args.target);

  if (args.rules || args.preset) {
    if (args.preset) ruleIds = ruleIds.concat(resolvePreset(String(args.preset)));
    if (args.rules) ruleIds = ruleIds.concat(list(args.rules));
  } else {
    const configPath = path.resolve(
      typeof args.config === "string" ? args.config : "polyrule.config.json"
    );
    if (fs.existsSync(configPath)) {
      const cfg = readJson(configPath);
      if (cfg.preset) ruleIds = ruleIds.concat(resolvePreset(cfg.preset));
      if (cfg.rules) ruleIds = ruleIds.concat(cfg.rules);
      if (!targets.length && cfg.targets) targets = cfg.targets;
    }
  }

  if (!targets.length || (targets.length === 1 && targets[0] === "all")) {
    targets = Object.keys(TARGETS);
  }

  return { ruleIds: dedupe(ruleIds), targets };
}

function main() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help) {
    console.log(HELP);
    return;
  }
  if (args.list) {
    printList();
    return;
  }
  if (args.check) {
    process.exit(runCheck() === 0 ? 0 : 1);
  }

  const { ruleIds, targets } = resolveConfig(args);

  if (!ruleIds.length) {
    console.error(
      "No rules selected. Use --preset, --rules, or a polyrule.config.json. Run --help."
    );
    process.exit(1);
  }

  const unknownTargets = targets.filter((t) => !TARGETS[t]);
  if (unknownTargets.length) {
    console.error(`Unknown target(s): ${unknownTargets.join(", ")}. Run --list.`);
    process.exit(1);
  }

  const rules = loadRules(ruleIds);
  const outDir = path.resolve(typeof args.out === "string" ? args.out : ".");
  const dryRun = Boolean(args["dry-run"]);

  console.log(
    `Polyrule: ${rules.length} rule module(s) -> ${targets.length} target(s)${
      dryRun ? " (dry run)" : ""
    }\n`
  );

  for (const targetKey of targets) {
    const target = TARGETS[targetKey];
    const content = render(target.format, rules);
    const dest = path.join(outDir, target.output);

    if (dryRun) {
      console.log(`  would write ${target.name.padEnd(28)} ${target.output}`);
      continue;
    }

    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, content, "utf8");
    console.log(`  wrote ${target.name.padEnd(28)} ${target.output}`);
  }

  console.log("\nDone.");
}

try {
  main();
} catch (err) {
  console.error(`Error: ${err.message}`);
  process.exit(1);
}
