// Polyrule test suite — run with: node --test
// Uses only Node built-ins (node:test, node:assert). No dependencies.

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

import {
  parseFrontmatter,
  resolvePreset,
  dedupe,
  formatMarkdown,
  formatMdc,
  allRuleIds,
  findRuleFile,
  normalize,
  CATALOG_DIR,
  TARGETS,
  PRESETS,
} from "./compile.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CLI = path.join(HERE, "compile.mjs");

function run(args, opts = {}) {
  try {
    const stdout = execFileSync("node", [CLI, ...args], {
      encoding: "utf8",
      cwd: opts.cwd || HERE,
    });
    return { code: 0, stdout };
  } catch (err) {
    return {
      code: err.status ?? 1,
      stdout: err.stdout?.toString() ?? "",
      stderr: err.stderr?.toString() ?? "",
    };
  }
}

function tmpDir() {
  return fs.mkdtempSync(path.join(os.tmpdir(), "polyrule-test-"));
}

// ---------- unit: frontmatter ----------

test("parseFrontmatter reads scalars, arrays, and quotes", () => {
  const meta = parseFrontmatter(
    ['id: my-rule', 'title: My Rule', 'tags: [a, b, c]', 'globs: ["**/*.ts", "**/*.tsx"]'].join(
      "\n"
    )
  );
  assert.equal(meta.id, "my-rule");
  assert.equal(meta.title, "My Rule");
  assert.deepEqual(meta.tags, ["a", "b", "c"]);
  assert.deepEqual(meta.globs, ["**/*.ts", "**/*.tsx"]);
});

test("parseFrontmatter keeps commas inside quoted array elements", () => {
  const meta = parseFrontmatter('globs: ["src/**/*.{ts,tsx}", "*.md"]');
  assert.deepEqual(meta.globs, ["src/**/*.{ts,tsx}", "*.md"]);
});

// ---------- unit: dedupe ----------

test("dedupe preserves first-seen order", () => {
  assert.deepEqual(dedupe(["a", "b", "a", "c", "b"]), ["a", "b", "c"]);
});

// ---------- unit: preset resolution ----------

test("every preset resolves and extends base where declared", () => {
  for (const name of Object.keys(PRESETS)) {
    const rules = resolvePreset(name);
    assert.ok(Array.isArray(rules) && rules.length > 0, `${name} resolves to rules`);
  }
});

test("resolvePreset throws on unknown preset", () => {
  assert.throws(() => resolvePreset("does-not-exist"), /Unknown preset/);
});

test("all preset rule references exist in the catalog", () => {
  const known = new Set(allRuleIds([CATALOG_DIR]));
  for (const name of Object.keys(PRESETS)) {
    for (const rid of resolvePreset(name)) {
      assert.ok(known.has(rid), `preset "${name}" references existing rule "${rid}"`);
    }
  }
});

// ---------- unit: formatters ----------

test("formatMarkdown includes the do-not-edit header and section titles", () => {
  const out = formatMarkdown([
    { id: "x", meta: { title: "Alpha" }, body: "- one" },
    { id: "y", meta: { title: "Beta" }, body: "- two" },
  ]);
  assert.match(out, /Generated by Polyrule/);
  assert.match(out, /## Alpha/);
  assert.match(out, /## Beta/);
});

test("formatMdc unions globs and scopes when globs present", () => {
  const out = formatMdc([
    { id: "x", meta: { title: "Alpha", globs: ["**/*.ts"] }, body: "- one" },
    { id: "y", meta: { title: "Beta", globs: ["**/*.tsx", "**/*.ts"] }, body: "- two" },
  ]);
  assert.match(out, /globs: \*\*\/\*\.ts, \*\*\/\*\.tsx/);
  assert.match(out, /alwaysApply: false/);
});

test("formatMdc omits empty globs line and applies always when no globs", () => {
  const out = formatMdc([{ id: "x", meta: { title: "Alpha" }, body: "- one" }]);
  assert.doesNotMatch(out, /globs:/);
  assert.match(out, /alwaysApply: true/);
});

// ---------- unit: catalog integrity ----------

test("no two targets write to the same output path", () => {
  const seen = new Map();
  for (const [name, t] of Object.entries(TARGETS)) {
    assert.ok(!seen.has(t.output), `${name} output "${t.output}" is unique`);
    seen.set(t.output, name);
  }
});

// ---------- integration: CLI ----------

test("--check exits 0 on a healthy catalog", () => {
  const r = run(["--check"]);
  assert.equal(r.code, 0);
  assert.match(r.stdout, /check: OK/);
});

test("--version prints the version and writes nothing", () => {
  const dir = tmpDir();
  try {
    const r = run(["--version"], { cwd: dir });
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stdout, /^polyrule \d+\.\d+\.\d+/);
    // A bare version query must not trigger a compile in the cwd.
    assert.deepEqual(fs.readdirSync(dir), []);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("-v is an alias for --version", () => {
  const r = run(["-v"]);
  assert.equal(r.code, 0, r.stderr);
  assert.match(r.stdout, /^polyrule \d+\.\d+\.\d+/);
});

test("an unknown flag fails fast and writes nothing", () => {
  const dir = tmpDir();
  try {
    const r = run(["--nope"], { cwd: dir });
    assert.equal(r.code, 1);
    assert.match(r.stderr, /Unknown option: --nope/);
    assert.deepEqual(fs.readdirSync(dir), []);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("an unknown short flag fails fast and writes nothing", () => {
  const dir = tmpDir();
  try {
    // -x must not be swallowed as --preset's value or slip through as a
    // positional; it has to trip the unknown-option guard like --nope does.
    const r = run(["--preset", "base", "-x", "--target", "claude"], { cwd: dir });
    assert.equal(r.code, 1, r.stdout);
    assert.match(r.stderr, /Unknown option/);
    assert.deepEqual(fs.readdirSync(dir), []);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

test("CLI --rules still honors targets from the config file", () => {
  const proj = tmpDir();
  try {
    fs.writeFileSync(
      path.join(proj, "polyrule.config.json"),
      JSON.stringify({ rules: ["core/security-baseline"], targets: ["claude"] })
    );
    // Selecting rules on the CLI must not discard config targets and fan out
    // to every target; only CLAUDE.md should be written.
    const r = run(["--rules", "core/security-baseline"], { cwd: proj });
    assert.equal(r.code, 0, r.stderr);
    const written = fs
      .readdirSync(proj)
      .filter((f) => f !== "polyrule.config.json");
    assert.deepEqual(written, ["CLAUDE.md"]);
  } finally {
    fs.rmSync(proj, { recursive: true, force: true });
  }
});

test("a rule id cannot escape the rules directory", () => {
  const proj = tmpDir();
  try {
    // Plant a file one level above the rules dir and try to reach it with ../.
    fs.writeFileSync(
      path.join(proj, "secret.md"),
      "---\nid: secret\ntitle: LEAK\n---\n\nTOP SECRET\n"
    );
    const rulesDir = path.join(proj, "rules");
    fs.mkdirSync(rulesDir, { recursive: true });
    const found = findRuleFile("../secret", [rulesDir]);
    assert.equal(found, null, "traversal id must not resolve to a file");
  } finally {
    fs.rmSync(proj, { recursive: true, force: true });
  }
});

test("--target accepts 'all' mixed with named targets", () => {
  const r = run(["--preset", "base", "--target", "cursor,all", "--dry-run"]);
  assert.equal(r.code, 0, r.stderr);
  // Expands to every target, so more than the two named appear.
  assert.match(r.stdout, /Claude Code/);
  assert.match(r.stdout, /Gemini CLI/);
});

test("unknown rule id fails with a clear error", () => {
  const r = run(["--rules", "core/nope", "--target", "claude", "--dry-run"]);
  assert.equal(r.code, 1);
  assert.match(r.stderr || r.stdout, /Rule not found/);
});

test("compile then --verify round-trips clean, and detects drift", () => {
  const out = tmpDir();
  try {
    const c = run(["--preset", "python-api", "--target", "claude,cursor", "--out", out]);
    assert.equal(c.code, 0, c.stderr);

    const v = run(["--preset", "python-api", "--target", "claude,cursor", "--out", out, "--verify"]);
    assert.equal(v.code, 0, "verify passes right after compile");
    assert.match(v.stdout, /up to date/);

    // Mutate a generated file -> verify should now fail.
    fs.appendFileSync(path.join(out, "CLAUDE.md"), "\nhand edit\n");
    const v2 = run(["--preset", "python-api", "--target", "claude,cursor", "--out", out, "--verify"]);
    assert.equal(v2.code, 1, "verify fails when a file drifts");
    assert.match(v2.stdout + (v2.stderr || ""), /STALE|out of date/);
  } finally {
    fs.rmSync(out, { recursive: true, force: true });
  }
});

test("project-local rules override the catalog and can add new modules", () => {
  const proj = tmpDir();
  const rulesDir = path.join(proj, "ai-rules", "local");
  try {
    fs.mkdirSync(rulesDir, { recursive: true });
    fs.writeFileSync(
      path.join(rulesDir, "company.md"),
      "---\nid: company\ntitle: Company Conventions\n---\n\n- Use tabs, not spaces.\n"
    );
    fs.writeFileSync(
      path.join(proj, "polyrule.config.json"),
      JSON.stringify({ rules: ["local/company"], rulesDir: "./ai-rules", targets: ["claude"] })
    );

    const c = run(["--out", proj], { cwd: proj });
    assert.equal(c.code, 0, c.stderr);
    const claude = fs.readFileSync(path.join(proj, "CLAUDE.md"), "utf8");
    assert.match(claude, /Company Conventions/);
    assert.match(claude, /Use tabs, not spaces/);
  } finally {
    fs.rmSync(proj, { recursive: true, force: true });
  }
});

test("findRuleFile respects directory precedence (local wins)", () => {
  const proj = tmpDir();
  try {
    const localDir = path.join(proj, "rules");
    fs.mkdirSync(path.join(localDir, "core"), { recursive: true });
    fs.writeFileSync(path.join(localDir, "core", "clean-code.md"), "local override");
    const found = findRuleFile("core/clean-code", [localDir, CATALOG_DIR]);
    assert.equal(found, path.join(localDir, "core", "clean-code.md"));
  } finally {
    fs.rmSync(proj, { recursive: true, force: true });
  }
});

test("normalize collapses CRLF so verify is line-ending agnostic", () => {
  assert.equal(normalize("a\r\nb"), "a\nb");
});
